"""Add dose reminders: patient dose_time and push subscriptions

Revision ID: 891c4f1ee866
Revises: a53bf50c312d
Create Date: 2026-09-24 13:12:54.401287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '891c4f1ee866'
down_revision = 'a53bf50c312d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('push_subscriptions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('p256dh', sa.Text(), nullable=False),
    sa.Column('auth', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint')
    )
    with op.batch_alter_table('push_subscriptions', schema=None) as batch_op:
        batch_op.create_index('push_subscriptions_user_idx', ['user_id'], unique=False)

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dose_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('last_reminder_sent_on', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_column('last_reminder_sent_on')
        batch_op.drop_column('dose_time')

    with op.batch_alter_table('push_subscriptions', schema=None) as batch_op:
        batch_op.drop_index('push_subscriptions_user_idx')

    op.drop_table('push_subscriptions')
    # ### end Alembic commands ###
