"""Add assigned_doctor_id to patients

Revision ID: a53bf50c312d
Revises: db43627a923c
Create Date: 2026-09-24 03:19:37.869044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a53bf50c312d'
down_revision = 'db43627a923c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_doctor_id', sa.UUID(as_uuid=False), nullable=True))
        batch_op.create_foreign_key(
            'patients_assigned_doctor_id_fkey', 'users', ['assigned_doctor_id'], ['id'], ondelete='SET NULL'
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_constraint('patients_assigned_doctor_id_fkey', type_='foreignkey')
        batch_op.drop_column('assigned_doctor_id')

    # ### end Alembic commands ###
