"""Initial schema

Revision ID: db43627a923c
Revises: 
Create Date: 2026-09-12 15:56:03.604778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db43627a923c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facilities',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('county', sa.Text(), nullable=True),
    sa.Column('sub_county', sa.Text(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('hospital', 'nurse', 'admin', 'viewer', 'patient')", name='users_role_check'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('patients',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.Text(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('facility', sa.Text(), nullable=True),
    sa.Column('tb_type', sa.Text(), nullable=True),
    sa.Column('regimen', sa.Text(), nullable=True),
    sa.Column('treatment_start', sa.Date(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('mdr_flag', sa.Boolean(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('registered_by', sa.UUID(as_uuid=False), nullable=True),
    sa.CheckConstraint("gender IN ('male', 'female', 'other')", name='patients_gender_check'),
    sa.CheckConstraint("status IN ('active', 'completed', 'lost', 'died')", name='patients_status_check'),
    sa.CheckConstraint("tb_type IN ('pulmonary', 'extra-pulmonary')", name='patients_tb_type_check'),
    sa.ForeignKeyConstraint(['registered_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.create_index('patients_status_idx', ['status'], unique=False)
        batch_op.create_index('patients_user_id_idx', ['user_id'], unique=False)

    op.create_table('profiles',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=True),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('hospital', 'nurse', 'admin', 'viewer', 'patient')", name='profiles_role_check'),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contacts',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('source_patient_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('relationship', sa.Text(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('screened', sa.Boolean(), nullable=False),
    sa.Column('screen_result', sa.Text(), nullable=True),
    sa.Column('screened_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("relationship IN ('spouse', 'child', 'parent', 'roommate', 'other')", name='contacts_relationship_check'),
    sa.CheckConstraint("screen_result IS NULL OR screen_result IN ('negative', 'referred', 'confirmed_tb')", name='contacts_screen_result_check'),
    sa.ForeignKeyConstraint(['source_patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.create_index('contacts_source_patient_idx', ['source_patient_id'], unique=False)

    op.create_table('dose_logs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('patient_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('taken', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('logged_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['logged_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id', 'date', name='dose_logs_patient_id_date_key')
    )
    with op.batch_alter_table('dose_logs', schema=None) as batch_op:
        batch_op.create_index('dose_logs_patient_date_idx', ['patient_id', 'date'], unique=False)

    op.create_table('lab_results',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('patient_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('test_type', sa.Text(), nullable=False),
    sa.Column('result', sa.Text(), nullable=False),
    sa.Column('result_date', sa.Date(), nullable=False),
    sa.Column('lab_ref', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('mdr_detected', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("result IN ('positive', 'negative', 'pending')", name='lab_results_result_check'),
    sa.CheckConstraint("test_type IN ('sputum_smear', 'genexpert', 'xray', 'culture')", name='lab_results_test_type_check'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lab_results', schema=None) as batch_op:
        batch_op.create_index('lab_results_patient_idx', ['patient_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab_results', schema=None) as batch_op:
        batch_op.drop_index('lab_results_patient_idx')

    op.drop_table('lab_results')
    with op.batch_alter_table('dose_logs', schema=None) as batch_op:
        batch_op.drop_index('dose_logs_patient_date_idx')

    op.drop_table('dose_logs')
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_index('contacts_source_patient_idx')

    op.drop_table('contacts')
    op.drop_table('profiles')
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_index('patients_user_id_idx')
        batch_op.drop_index('patients_status_idx')

    op.drop_table('patients')
    op.drop_table('users')
    op.drop_table('facilities')
    # ### end Alembic commands ###
